# Generated by Django 4.0 on 2022-06-29 12:05

from django.db import migrations, models
import django.db.models.deletion
import mainbackend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30, null=True)),
                ('test_amount', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('W', 'Waiting for parameters'), ('O', 'Open'), ('C', 'Close')], max_length=1)),
                ('exam_code', models.CharField(default=mainbackend.models.create_invite_code, max_length=8, null=True, unique=True)),
                ('creator_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('exam_finished', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True)),
                ('exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField(verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.DecimalField(decimal_places=0, max_digits=1, null=True)),
                ('parameter_1', models.CharField(max_length=30, null=True)),
                ('parameter_2', models.CharField(max_length=30, null=True)),
                ('parameter_3', models.CharField(max_length=30, null=True)),
                ('parameter_4', models.CharField(max_length=30, null=True)),
                ('parameter_5', models.CharField(max_length=30, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileset_name', models.CharField(max_length=50, unique=True)),
                ('fileset_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('file_labels', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('function', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('question', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=30, null=True)),
                ('result_number', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('exam_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.examtest')),
                ('examination_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.examinationresult')),
            ],
        ),
        migrations.CreateModel(
            name='FileDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('file_label', models.CharField(max_length=150)),
                ('file_destination', models.CharField(max_length=150)),
                ('file_number', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.fileset')),
            ],
        ),
        migrations.AddField(
            model_name='examtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.test'),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.examinedperson'),
        ),
        migrations.CreateModel(
            name='AdminToExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.adminacc')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam')),
            ],
        ),
    ]
