# Generated by Django 3.2.8 on 2021-10-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.test')),
            ],
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='exam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.examinedperson'),
        ),
    ]
