# Generated by Django 3.2.8 on 2021-10-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0002_auto_20211019_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AdminToExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.adminacc')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam')),
            ],
        ),
    ]
