# Generated by Django 4.0 on 2022-06-30 08:10

from django.db import migrations, models
import mainbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminacc',
            name='password',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(default=mainbackend.models.create_invite_code, max_length=10, null=True, unique=True),
        ),
    ]
