# Generated by Django 3.2.8 on 2021-11-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0003_auto_20211019_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='test1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbackend.test'),
        ),
    ]
