# Generated by Django 3.2.8 on 2021-11-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0004_auto_20211101_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='test1_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbackend.testtype'),
        ),
    ]
