# Generated by Django 3.2.8 on 2021-11-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0005_auto_20211104_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1_result', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='results_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbackend.results'),
        ),
    ]
