# Generated by Django 3.2.8 on 2021-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0006_auto_20211105_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='testtype',
            name='test_type_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
