# Generated by Django 3.2.8 on 2021-11-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0007_auto_20211116_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtype',
            old_name='description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='testtype',
            old_name='name',
            new_name='name',
        ),
    ]
