# Generated by Django 3.2.8 on 2021-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0009_auto_20211117_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='question',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
