# Generated by Django 3.2.8 on 2021-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0010_testtype_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_amount',
            field=models.IntegerField(null=True),
        ),
    ]
