# Generated by Django 3.2.8 on 2021-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0012_test_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='first_btn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='second_btn',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
