# Generated by Django 4.0 on 2022-02-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0013_auto_20211130_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinedperson',
            old_name='start_date',
            new_name='birth_date',
        ),
    ]
