# Generated by Django 4.0 on 2022-02-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0014_rename_start_date_examinedperson_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileset_name', models.CharField(max_length=50)),
                ('fileset_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MUSHRATestSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=50)),
                ('original_file_label', models.CharField(max_length=50)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.fileset')),
            ],
        ),
    ]
