# Generated by Django 4.0 on 2022-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0015_fileset_mushratestsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='first_btn',
        ),
        migrations.RemoveField(
            model_name='test',
            name='second_btn',
        ),
    ]
