# Generated by Django 4.0 on 2022-02-20 19:21

from django.db import migrations, models
import mainbackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0016_remove_test_first_btn_remove_test_second_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(default=mainbackend.models.create_invite_code, max_length=6, null=True, unique=True),
        ),
    ]
