# Generated by Django 4.0 on 2022-02-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0017_exam_exam_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=30, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.exam')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.test')),
            ],
        ),
    ]
