# Generated by Django 4.0 on 2022-02-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0018_examtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test1_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='test1_type',
        ),
    ]
