# Generated by Django 4.0 on 2022-02-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0019_remove_exam_test1_id_remove_exam_test1_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtest',
            name='test_number',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
