# Generated by Django 4.0 on 2022-03-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0021_result_remove_examinationresult_results_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('file_label', models.CharField(max_length=150)),
                ('file_destination', models.CharField(max_length=150)),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbackend.fileset')),
            ],
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='exam_finished',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', 'Cancelled')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='MUSHRATestSets',
        ),
    ]
