# Generated by Django 4.0 on 2022-03-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0023_rename_admin_id_admintoexam_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedestination',
            old_name='file_name',
            new_name='filename',
        ),
    ]
