# Generated by Django 4.0 on 2022-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0025_fileset_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedestination',
            name='file_number',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
