# Generated by Django 4.0 on 2022-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0027_result_result_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting for parameters'), ('O', 'Open'), ('C', 'Close')], max_length=1),
        ),
    ]
