# Generated by Django 4.0 on 2022-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0028_alter_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtest',
            old_name='parameter',
            new_name='parameter_1',
        ),
        migrations.AddField(
            model_name='examtest',
            name='parameter_2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
