# Generated by Django 4.0 on 2022-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0029_rename_parameter_examtest_parameter_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileset',
            name='fileset_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
