# Generated by Django 4.0 on 2022-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0030_alter_fileset_fileset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtest',
            name='parameter_3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examtest',
            name='parameter_4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examtest',
            name='parameter_5',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
