# Generated by Django 4.0 on 2022-04-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0032_fileset_filename_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileset',
            old_name='filename_list',
            new_name='file_labels',
        ),
    ]
