# Generated by Django 4.0 on 2022-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbackend', '0033_rename_filename_list_fileset_file_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='creator_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='exam_finished',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
